package com.radeksukup.shoppinglist2;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;

public class DatabaseHelper extends SQLiteOpenHelper {
	
	private static final String DATABASE_NAME = "shoppingList.db";
	private static final int DATABASE_VERSION = 12;
	
	public static final String CATEGORIES_TABLE = "categories";
	public static final String CATEGORY_COLUMN_ID = "id";
	public static final String CATEGORY_COLUMN_TITLE = "title";
	
	public static final String PRODUCTS_TABLE = "products";
	public static final String PRODUCT_COLUMN_ID = "id";
	public static final String PRODUCT_COLUMN_TITLE = "title";
	public static final String PRODUCT_COLUMN_CATEGORY_ID = "categoryId";
	
	private static final String TABLE_CATEGORIES_CREATE = "CREATE TABLE " + CATEGORIES_TABLE + " ( " + CATEGORY_COLUMN_ID + " INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, " + CATEGORY_COLUMN_TITLE + " VARCHAR(50) NOT NULL );";
	private static final String TABLE_PRODUCTS_CREATE = "CREATE TABLE " + PRODUCTS_TABLE + " ( " + PRODUCT_COLUMN_ID + " INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, " + PRODUCT_COLUMN_TITLE + " VARCHAR(50) NOT NULL, " + PRODUCT_COLUMN_CATEGORY_ID + " INT NOT NULL );";

	public DatabaseHelper(Context context) {
		super(context, DATABASE_NAME, null, DATABASE_VERSION);
	}

	@Override
	public void onCreate(SQLiteDatabase db) {
		db.execSQL(TABLE_CATEGORIES_CREATE);
		db.execSQL(TABLE_PRODUCTS_CREATE);
		db.execSQL("INSERT INTO categories (id, title) VALUES (null, 'Ovoce');");
		db.execSQL("INSERT INTO categories (id, title) VALUES (null, 'Zelenina');");
		db.execSQL("INSERT INTO categories (id, title) VALUES (null, 'Pečivo');");
		db.execSQL("INSERT INTO categories (id, title) VALUES (null, 'Konzervy, zavařeniny, dresingy')");
		db.execSQL("INSERT INTO categories (id, title) VALUES (null, 'Maso, uzeniny')");
		db.execSQL("INSERT INTO categories (id, title) VALUES (null, 'Mléčné výrobky, sýry')");
		db.execSQL("INSERT INTO categories (id, title) VALUES (null, 'Rýže, těstoviny, luštěniny')");
		db.execSQL("INSERT INTO categories (id, title) VALUES (null, 'Sladkosti, slanosti')");
		db.execSQL("INSERT INTO categories (id, title) VALUES (null, 'Nealko nápoje')");
		db.execSQL("INSERT INTO categories (id, title) VALUES (null, 'Alkoholické nápoje')");
		db.execSQL("INSERT INTO categories (id, title) VALUES (null, 'Mražené výrobky')");
		db.execSQL("INSERT INTO categories (id, title) VALUES (null, 'Koření, ochucovadla, pečení')");
	    db.execSQL("INSERT INTO categories (id, title) VALUES (null, 'Drogerie, Hygienické potřeby')");
	    db.execSQL("INSERT INTO categories (id, title) VALUES (null, 'Domácí potřeby')");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Ananas', 1)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Jablka', 1)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Banány', 1)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Pomeranče', 1)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Mandarinky', 1)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Hroznové víno bílé', 1)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Hroznové víno červené', 1)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Kiwi', 1)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Hrušky', 1)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Jahody', 1)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Pomelo', 1)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Švestky', 1)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Rajčata', 2)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Rajčata cherry', 2)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Brambory', 2)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Okurka (hadovka)', 2)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Okurky kyselé', 2)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Cibule', 2)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Křen praný', 2)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Salát hlávkový', 2)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Česnek', 2)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Paprika žlutá', 2)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Paprika červená', 2)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Paprika zelená', 2)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Paprika oranžová', 2)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Paprika bílá', 2)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Paprika kapie', 2)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Ledový salát', 2)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Římský salát', 2)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Zelí červené', 2)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Zelí bílé', 2)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Cibule šalotka', 2)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Cibulka jarní', 2)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Celer', 2)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Petržel', 2)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Mrkev', 2)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Meloun červený', 1)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Meloun žlutý', 1)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Mango', 1)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Citróny', 1)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Limetky', 1)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Lichi', 1)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Maliny', 1)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Borůvky', 1)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Ostružiny', 1)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Čínské zelí', 2)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Grep', 1)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Meruňky', 1)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Broskve', 1)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Nektarinky', 1)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Višně', 1)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Třešně', 1)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Žampiony', 2)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Ředkev', 2)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Zázvor', 2)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Kedlubny', 2)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Chleba', 3)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Toastový chleba', 3)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Rohlíky', 3)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Rohlíky celozrnné', 3)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Housky', 3)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Housky celozrnné', 3)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Koblihy', 3)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Koláčky', 3)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Croissant', 3)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Bageta velká', 3)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Bageta malá', 3)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Jablečný kompot', 4)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Meruňkový kompot', 4)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Švestkový kompot', 4)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Jahodový kompot', 4)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Broskový kompot', 4)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Hruškový kompot', 4)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Mandarinkový kompot', 4)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Borůvkový kompot', 4)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Brusinkový kompot', 4)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Aloe vera kompot', 4)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Jablečné pyré', 4)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Džem jahodový', 4)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Džem meruňkový', 4)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Džem borůvkový', 4)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Džem malinový', 4)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Džem lesní směs', 4)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Med', 4)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Ananas kousky', 4)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Ananas plátky', 4)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Kukuřice', 4)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Fazole červené', 4)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Fazole bílé', 4)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Olivy černé', 4)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Olivy zelené', 4)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Hrášek', 4)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Rajčata loupaná celá', 4)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Rajčata loupaná krájená', 4)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Rajčata sušená', 4)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Rajčatový protlak', 4)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Žampiony celé', 4)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Žampiony krájené', 4)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Chřest', 4)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Cizrna v nálevu', 4)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Čočka v nálevu', 4)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Mrkev sterilovaná', 4)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Česnek sterilovaný', 4)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Celer sterilovaný', 4)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Cibulky sterilované', 4)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Červená řepa', 4)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Zelí bílé sterilované', 4)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Zelí červené sterilované', 4)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Zelí kysané', 4)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Tuňáková konzerva', 4)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Sardinky', 4)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Sleď', 4)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Hořčice plnotučná', 4)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Hořčice kremžská', 4)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Kečup sladký', 4)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Kečup ostrý', 4)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Křen', 4)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Chilli omáčka', 4)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Šunka', 5)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Šunka uzená', 5)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Vysočina', 5)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Herkules', 5)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Turisťák', 5)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Poličan', 5)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Paprikáš', 5)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Tlačenka', 5)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Párky', 5)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Špekáčky', 5)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Klobása', 5)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Vepřová kýta', 5)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Veprová pečeně', 5)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Vepřová plec', 5)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Vepřová játra', 5)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Vepřové kotlety', 5)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Vepřové ledviny', 5)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Vepřový bok s kostí', 5)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Vepřový bok bez kosti', 5)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Krkovice', 5)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Vepřová panenka', 5)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Hovězí svíčková', 5)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Hovězí falešná svíčková', 5)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Hovězí zadní', 5)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Hovězí přední', 5)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Hovězí roštěná', 5)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Mleté vepřové', 5)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Mleté vepřové + hovězí', 5)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Mleté hovězí', 5)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Hovězí dršťky', 5)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Hovězí krk', 5)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Hovězí kližka bez kosti', 5)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Hovězí plec bez kosti', 5)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Kuřecí křídla', 5)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Kuřecí stehna', 5)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Kuřecí stehna spodní', 5)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Kuřecí stehna horní', 5)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Kuřecí stehna uzená', 5)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Kuře', 5)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Kuře uzené', 5)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Kuřecí řízek prsní', 5)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Kuřecí řízek stehenní', 5)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Kuřecí motýlek', 5)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Krůtí křídla', 5)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Krůtí řízek prsní', 5)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Krůtí stehno', 5)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Kuřecí játra', 5)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Kuřecí krky', 5)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Losos filet s kůží', 5)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Losos filet bez kůže', 5)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Králík', 5)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Anglická slanina', 5)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Špek', 5)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Mléko polotučné', 6)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Mléko odtučněné', 6)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Mléko plnotučné', 6)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Smetana na vaření', 6)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Smetana ke šlehání', 6)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Šlehačka ve spreji', 6)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Smetana do kávy', 6)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Smetana zakysaná', 6)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Jogurt bílý', 6)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Jogurt ovocný', 6)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Tvaroh měkký', 6)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Tvaroh polotučný', 6)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Tvaroh tučný', 6)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Tvaroh ochucený', 6)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Mléčná rýže', 6)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Mléčná rýže ovocná', 6)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Dezert pudingový', 6)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Kefírové mléko', 6)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Kefírové mléko ochucené', 6)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Acidofilní mléko', 6)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Acidofilní mléko ochucené', 6)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Podmáslí', 6)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Jogurtový nápoj', 6)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Ledová káva', 6)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Vejce', 6)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Droždí', 6)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Máslo', 6)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Pomazánkové máslo', 6)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Margarín', 6)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Tuk na pečení', 6)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Majonéza', 6)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Tatarka', 6)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Balkánský sýr', 6)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Sýr plátky', 6)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Sýr uzený', 6)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Sýr cihla', 6)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Tavený sýr', 6)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Niva', 6)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Parmezán', 6)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Mozarella', 6)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Zottarella', 6)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Olomoucké syrečky', 6)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Hermelín', 6)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Modřenín', 6)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Parenica', 6)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Pepa na gril', 6)");;
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Blaťácké zlato', 6)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Cottage sýr', 6)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Rýže', 7)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Rýže jasmínová', 7)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Rýže divoká', 7)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Rýže basmati', 7)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Rýže kulatozrnná', 7)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Rýže sushi', 7)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Čočka', 7)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Čočka červená', 7)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Hrách', 7)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Jáhly', 7)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Pohanka', 7)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Sója', 7)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Bulgur', 7)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Kuskus', 7)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Špagety', 7)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Kolínka', 7)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Penne', 7)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Nudle', 7)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Nudle polévkové', 7)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Čínské nudle', 7)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Rýžové nudle', 7)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Tagliatelle', 7)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Makarony', 7)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Noky', 7)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Vřetena', 7)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Čokoláda mléčná', 8)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Čokoláda hořká', 8)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Čokoláda na vaření', 8)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Piškoty', 8)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Musli tyčinka', 8)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Ovesné vločky', 8)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Ovesná kaše', 8)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Cereálie', 8)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Bebe sušenky', 8)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Trubičky', 8)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Twix', 8)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Mars', 8)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Snickers', 8)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Mila', 8)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Banány v čokoládě', 8)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Polomáčené sušenky', 8)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Bonbony', 8)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Žvýkačky', 8)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Chipsy', 8)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Tyčinky slané', 8)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Tyčinky sýrové', 8)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Tyčinky bramborové', 8)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, '3Bit', 8)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Kinder Maxi King', 8)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Kinder Bueno', 8)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Kofila', 8)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Kik Kat', 8)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Lion', 8)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Milky Way', 8)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Deli', 8)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Margot', 8)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Sójové řezy', 8)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Disko sušenky', 8)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Florenta', 8)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Esíčka', 8)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Kakaové řezy', 8)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Bersi', 8)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Křupky', 8)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Bake rolls', 8)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Tuc', 8)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Arašídy', 8)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Popcorn slaný', 8)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Popcorn máslový', 8)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Popcorn sýrový', 8)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Popcorn slaninový', 8)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Popcorn sladký', 8)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Kešu oříšky', 8)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Pistácie', 8)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Mandle solené', 8)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Voda perlivá', 9)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Voda neperlivá', 9)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Voda jemně perlivá', 9)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Čaj černý', 9)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Čaj ovocný', 9)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Čaj zelený', 9)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Energetický nápoj', 9)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Káva', 9)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Džus jablečný', 9)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Džus multivitamín', 9)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Džus černý rybíz', 9)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Džus jahodový', 9)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Džus brusinkový', 9)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Džus hruškový', 9)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Ledový čaj', 9)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Sirup', 9)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Pepsi', 9)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, '7UP', 9)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Top topic', 9)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Tonic', 9)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Coca Cola', 9)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Coca Cola zero', 9)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Coca Cola light', 9)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Sprite', 9)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Fanta', 9)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Kofola', 9)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Pivo', 10)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Víno červené', 10)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Víno bílé', 10)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Víno růžové', 10)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Metaxa', 10)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Stará myslivecká', 10)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Gin', 10)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Tequila stříbrná', 10)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Tequila zlatá', 10)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Borovička', 10)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Slivovice', 10)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Hruškovice', 10)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Meruňkovice', 10)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Třešňovice', 10)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Tuzemák', 10)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Vodka', 10)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Captain morgan', 10)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Fernet', 10)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Fernet citrus', 10)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Whisky', 10)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Vaječný koňak', 10)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Zelená', 10)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Becherovka', 10)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Becherovka lemond', 10)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Jagermeister', 10)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Magister', 10)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Malibu', 10)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Šampaňské', 10)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Bacardi', 10)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Key rum', 10)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Havana', 10)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Hennessy', 10)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Absinth', 10)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Griotka', 10)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Baileys', 10)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Hranolky', 11)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Hamburgery mražené', 11)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Listové těsto', 11)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Mrkev mražená', 11)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Hrášek mražený', 11)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Špenát mražený', 11)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Kukuřice mražená', 11)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Rybí prsty', 11)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Kuře mražené', 11)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Zmrzlina', 11)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Nanuky', 11)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Pizza', 11)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Čínská směs mražená', 11)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Babiččina směs mražená', 11)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Polévková směs mražená', 11)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Francouzská směs mražená', 11)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Letní směs mražená', 11)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Zeleninová směs mražená', 11)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'WOK směs', 11)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Brokolice mražená', 11)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Jahody mražené', 11)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Maliny mražené', 11)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Borůvky mražené', 11)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Dršťková polévka', 11)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Játrové knedlíčky', 11)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Játra mražená', 11)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Kachna mražená', 11)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Puding vanilkový', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Puding čokoládový', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Puding jahodový', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Puding malinový', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Puding banánový', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Sůl', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Sůl mořská', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Pepř mletý', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Pepř celý', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Nové koření', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Bobkový list', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Paprika sladká mletá', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Paprika pálivá mletá', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Paprika gulášová mletá', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Chilli koření', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Kari', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Kmín', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Sušený česnek', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Majoránka', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Bazalka', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Oregano', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Grilovací koření', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Koření na ryby', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Koření na steak', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Hřebíček', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Koření na kuře', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Skořice mletá', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Skořice celá', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Vanilka bourbon', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Jalovec', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Libeček', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Rozmarýn', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Fenykl', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Petrželka', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Zázvor mletý', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Tymián', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Muškátový květ', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Muškátový ořech', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Anýz', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Badyán mletý', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Badyán celý', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Hořčičné semínko', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Pažitka', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Petrželová nať', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Římský kmín', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Provensálské koření', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Sójová omáčka', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Worcestrová omáčka', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Polévkové koření', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Podravka', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Jíška tmavá', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Jíška světlá', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Mouka hladká', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Mouka hrubá', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Mouka polohrubá', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Olej', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Ocet', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Kypřící prášek', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Prášek do pečiva', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Skořicový cukr', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Vanilkový cukr', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Švestková povidla', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Jablečná povidla', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Jablečné pyré', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Cukrářská poleva', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Vanilkové aroma', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Punčové aroma', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Kokosové aroma', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Rumové aroma', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Jedlá soda', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Kyselina citrónová', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Želé cukrárenské', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Solamyl', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Bujón hovězí', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Bujón zeleninový', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Bujón kuřecí', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Bujón gulášový', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Bujón houbový', 12)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Mýdlo', 13)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Mýdlo tekuté', 13)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'WC papír', 13)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'WC blok', 13)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Šampón', 13)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Sprchový gel', 13)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Žiletky', 13)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Tampóny', 13)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Tampóny odličovací', 13)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Tyčinky do uší', 13)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Deodorant', 13)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Prášek na prání', 13)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Aviváž', 13)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Osvěžovač vzduchu ve spreji', 13)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Osvěžovač vzduchu tuhý', 13)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Odstraňovač skvrn', 13)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Jar na nádobí', 13)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Tablety do myčky', 13)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Leštidlo do myčky', 13)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Savo', 13)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Savo ve spreji', 13)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Savo na textil', 13)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Tekutý písek', 13)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Ubrousky', 13)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Čistič na okna', 13)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Kuchyňské utěrky', 13)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Pronto', 13)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Čistič na podlahy', 13)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Čistič na WC', 13)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Čistič odpadů', 13)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Čistič na vodní kámen', 13)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Kapesníčky', 13)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Gel na vlasy', 13)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Lak na vlasy', 13)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Vosk na vlasy', 13)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Kondicionér', 13)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Barva na vlasy', 13)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Opalovací krém', 13)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Balzám na rty', 13)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Pěna do koupele', 13)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Kartáček na zuby', 13)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Zubní pasta', 13)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Ústní voda', 13)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Lak na nehty', 13)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Pěna na holení', 13)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Balzám po holení', 13)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Kondomy', 13)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Nůžky na nehty', 13)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Vložky', 13)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Alobal', 14)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Papír na pečení', 14)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Pytle na odpadky', 14)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Houbičky na nádobí', 14)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Smetáček a lopatka', 14)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Fólie', 14)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Svíčka', 14)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Lepící páska', 14)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Sklenice', 14)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Hrnek', 14)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Hrnec', 14)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Pánev', 14)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Cedník', 14)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Plastová miska', 14)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Příbory', 14)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Prkénko', 14)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Lis na česnek', 14)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Naběračka', 14)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Nůžky', 14)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Otvírák na konzervy', 14)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Otvírák na pivo', 14)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Vývrtka', 14)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Talíř hluboký', 14)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Talíř mělký', 14)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Talíř malý', 14)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Mlýnek na maso', 14)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Kýbl', 14)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Žehlička', 14)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Žehlící prkno', 14)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Deka', 14)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Prostěradlo', 14)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Drátěnka', 14)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Prachovka', 14)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Gumové rukavice', 14)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Utěrka univerzální', 14)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Lavor', 14)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Prostírání na stůl', 14)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Ručník', 14)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Žárovka', 14)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Rychlovarná konvice', 14)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Baterie AA', 14)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Baterie AAA', 14)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Vteřinové lepidlo', 14)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Izolační páska', 14)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Elektrikářská páska', 14)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Silikon', 14)");
	    db.execSQL("INSERT INTO products (id, title, categoryId) VALUES (null, 'Utěrka na nádobí', 14)");
	}

	@Override
	public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
		Log.w(DatabaseHelper.class.getName(),
				"Upgrading database from version " + oldVersion + " to " + newVersion + ", which will destroy all old data");
		db.execSQL("DROP TABLE IF EXISTS categories;");
		db.execSQL("DROP TABLE IF EXISTS products;");
		onCreate(db);
	}

}